# Generated by Django 5.1.4 on 2024-12-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDGPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='sotildi_sotilmadi',
            field=models.BooleanField(null=True),
        ),
    ]
