# Generated by Django 6.1.1 on 2026-09-24 08:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDGPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugalteriya',
            name='abonent_tolov',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bugalteriya',
            name='sim_karta_tolov',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bugalteriya',
            name='yil',
            field=models.IntegerField(help_text="Yil 2000 va hozirgi yil orasida bo'lishi kerak.", validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='sana',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
